package com.root.controllers;

import com.root.accessingdatamysql.UserRepository;
import com.root.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/")
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping()
    public String indexPage(){return "index";}

    @GetMapping("/index")
    public String indexPageToo(){return "index";}

    @GetMapping("/login")
    public String loginPage() {return "login";}

    @GetMapping("/registration")
    public String registrationPage(@ModelAttribute("user") User user){

        return "register";
    }

    @GetMapping("/admin")
    public String adminPage(){return "admin";}

    @PostMapping(path = "/create") // Map ONLY POST Requests
    public @ResponseBody String addNewUser(@ModelAttribute ("user") User user, BindingResult bindingResult) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        if (bindingResult.hasErrors()){
            return "/registration";
        }

        userRepository.save(user);
        return "redirect:/admin";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
